/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects; it is checked in here
// so TypeScript has the expected ambient types from the first install.

